# Site settings
title: Untra - Samuel Volin
description: "Programmer, Mathematician, "
url: "https://untra.io"
author:
  name: "Samuel Volin"
  email: "sam@untra.io"
  url: "https://untra.io"

# Build settings
baseurl: "" # Change this to your relative path (ex: /blog), or leave it empty
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default layout values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate

# Keywords
keywords:
  - Samuel
  - Volin
  - Developer
  - Software Engineer
  - Super Gorgeous Programmer
  - Like Seriously You Should Date Him
  - so hawt
  - Colorado
  - Denver
  - Boulder
  - Golang
  - Typescript
  - Elixir
  - Badass
  - quinoa
  - Computer Science
  - Mathematics
  - University
  - Untra
  - StackHawk
  - LogRhythm
  - Application Security
  - Fullstack
  - Software Engineering
  - super science

reverse: true

# set this to enable google analytics
ga_id: 'UA-73082006-1'
ga_domain: 'auto'

# off-site navigations under the hosted
navitems:
  - [ "ğŸ”Naiveasync", "https://naiveasync.untra.io/"]
  - [ "ğŸ±Naivetable", "https://naivetable.untra.io/"]
  - [ "ğŸ’¬Jekyll Polyglot", "https://polyglot.untra.io/"]
  - [ "ğŸ“·Sammich in Israel", "http://israelsammich.blogspot.com/"]
  - [ "ğŸ’¾Colorado CompSci", "https://cocompsci.blogspot.com/"]


# In case you ever wanted to find me?
links:
  twitter: untra
  email: sam@untra.io
  github: untra
  reddit: untra
  keybase: untra
  mixcloud: untra
  linkedin: untra
